name: Build Wii U WUHB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Install devkitPro Tools
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/devkitPro/installer/releases/download/v3.0.3/devkitpro-pacman-installer.exe" -OutFile "dkp-install.exe"
          Start-Process -FilePath ".\dkp-install.exe" -ArgumentList "/S" -Wait
          $env:PATH += ";C:\devkitPro\pacman\bin"
          dkp-pacman -Sy
          dkp-pacman -S --noconfirm wiiu-dev wuhbtool

      - name: Run Build Script
        shell: cmd
        run: |
          set DEVKITPRO=/opt/devkitpro
          set DEVKITPPC=%DEVKITPRO%/devkitPPC
          set PATH=C:\devkitPro\tools\bin;C:\devkitPro\devkitPPC\bin;%PATH%
          call build.bat
        env:
          DEVKITPRO: C:\devkitPro

      - name: Upload WUHB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deltarune-wuhb
          path: output-wiiu/
