name: Build Wii U WUHB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install devkitPro via Chocolatey
        shell: powershell
        run: |
          choco install devkitpro-pacman -y
          $env:Path += ";C:\devkitPro\pacman\bin"
          & "C:\devkitPro\pacman\bin\dkp-pacman.exe" -Syy --noconfirm
          & "C:\devkitPro\pacman\bin\dkp-pacman.exe" -S --noconfirm wiiu-dev wuhbtool

      - name: Run Build Script
        shell: cmd
        run: |
          set DEVKITPRO=C:\devkitPro
          set DEVKITPPC=%DEVKITPRO%\devkitPPC
          set PATH=%DEVKITPRO%\tools\bin;%DEVKITPRO%\pacman\bin;%DEVKITPPC%\bin;%PATH%
          call build.bat
